# Generated by Django 4.2.7 on 2025-11-11 15:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('purchase_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('indicators', models.JSONField(default=dict)),
                ('recommendation', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold')], default='hold', max_length=10)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ollama_reasoning', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_analyses', to='cryptos.crypto')),
            ],
            options={
                'ordering': ['-analysis_date'],
                'get_latest_by': 'analysis_date',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('open_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='cryptos.crypto')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['crypto', '-timestamp'], name='cryptos_pri_crypto__fedba6_idx')],
                'unique_together': {('crypto', 'timestamp')},
            },
        ),
    ]
