# Generated by Django 4.2.7 on 2025-11-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_update_prices', models.BooleanField(default=False, help_text='Enable automatic price updates')),
                ('price_update_interval', models.IntegerField(default=60, help_text='Price update interval in minutes')),
                ('auto_run_analysis', models.BooleanField(default=False, help_text='Enable automatic technical analysis')),
                ('analysis_interval', models.IntegerField(default=360, help_text='Analysis interval in minutes')),
                ('ollama_base_url', models.CharField(default='http://ollama.logicpulse.com:11434', max_length=200)),
                ('ollama_model', models.CharField(default='llama3', max_length=100)),
                ('historical_days', models.IntegerField(default=30, help_text='Number of days of historical data for analysis')),
                ('last_price_update', models.DateTimeField(blank=True, null=True)),
                ('last_analysis_run', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Settings',
                'verbose_name_plural': 'App Settings',
            },
        ),
    ]
