# Generated by Django 4.2.7 on 2025-11-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptos', '0002_appsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='ollama_base_url',
            field=models.CharField(default='https://ollama.logicpulse.com', max_length=200),
        ),
    ]
