# Generated by Django 4.2.7 on 2025-11-11 15:57

from django.db import migrations


def update_ollama_urls(apps, schema_editor):
    """Update existing AppSettings to use HTTPS URL"""
    AppSettings = apps.get_model('cryptos', 'AppSettings')
    for settings in AppSettings.objects.all():
        if settings.ollama_base_url == 'http://ollama.logicpulse.com:11434':
            settings.ollama_base_url = 'https://ollama.logicpulse.com'
            settings.save()


def reverse_update(apps, schema_editor):
    """Reverse migration - not really needed but good practice"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cryptos', '0003_alter_appsettings_ollama_base_url'),
    ]

    operations = [
        migrations.RunPython(update_ollama_urls, reverse_update),
    ]
