# Generated by Django 4.2.7 on 2025-11-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptos', '0004_update_ollama_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='ollama_model',
            field=models.CharField(default='plutus', max_length=100),
        ),
    ]
